# This config defines the environment for the training loop. This includes the Simulator entity, type of platform, path
# to the directory in which components (Sensors, Controllers, and Simulators) are registered with the PluginLibrary.
{
  "horizon": 1000,
  "simulator": { "type": "PongSimulator", "config": {}},
  "plugin_paths": ["corl"],
  "episode_parameter_provider":
    {
      "type": "corl.episode_parameter_providers.simple.SimpleParameterProvider",
    },
  "simulator_reset_parameters": {
    "pong": {
      "ball": {
          "x_vel": {
            'type': 'corl.libraries.parameters.RandomSignUniformParameter',
            'config': {
              'low': 3,
              'high': 5,
              'health_enabled': False
            },
          },
      },
    },
      "paddle0_side":
        {
          "type": "corl.libraries.parameters.ChoiceParameter",
          "config":
            { "name": "side", "units": None, "choices": ["left"] },
        },
      "platforms":
        {
          "paddle0":
            {
              "y_and_vel": {
                "type": "corl.libraries.parameters.PassthroughParameterWrapper",
                "config": {
                },
                "wrapped": {
                    "y":
                      {
                        "type": "corl.libraries.parameters.ConstantParameter",
                        "config": { "value": 10 },
                      },
                    "vel":
                      {
                        "type": "corl.libraries.parameters.ConstantParameter",
                        "config": { "value": 10 },
                      },
                  },
              }
            },
          "paddle1":
            {
              "y":
                {
                  "type": "corl.libraries.parameters.ConstantParameter",
                  "config": { "value": 10 },
                },
              "vel":
                {
                  "type": "corl.libraries.parameters.ConstantParameter",
                  "config": { "value": 10 },
                },
            },
        },
    },
  "reference_store":
    {
      "target_side":
        {
          "type": "corl.libraries.parameters.ChoiceParameter",
          "config": { "choices": [0, 1] },
        },
    },
}
