# ---------------------------------------------------------------------------
#
#
# Air Force Research Laboratory (AFRL) Autonomous Capabilities Team (ACT3)
# Reinforcement Learning (RL) Core.
#
# This is a US Government Work not subject to copyright protection in the US.
#
# The use, dissemination or disclosure of data in this file is subject to
# limitation or restriction. See accompanying README and LICENSE for details.
# ---------------------------------------------------------------------------

# === Execution ===
rollout_fragment_length: 180
train_batch_size: 12000  # set to num_workers * rollout_fragment_length

# === Resources ===
num_workers: 6
num_cpus_per_worker: 1
num_gpus_per_worker: 0
num_envs_per_worker: 1

custom_resources_per_worker: {}

num_cpus_for_driver: 2
num_gpus: 0

# === PPO ===
num_sgd_iter: 30
sgd_minibatch_size: 1200
batch_mode: complete_episodes

# === Other ===
seed: 1
framework: torch

# === Eval While Training ===
# evaluation_interval: 1
# evaluation_duration: 100
# evaluation_num_workers: 1 # This is in addition to num_workers
# evaluation_duration_unit: episodes
