# This config defines parameters used to initialize the agent, including platform parts, initial state
# (simulator_reset_parameters), glues, dones, and rewards.

"agent": "corl.agents.simple_multi_platform_agent.SimpleMultiPlatform"
"config":
    {
        "parts":
            [
                [
                    { "part": "PaddleController" },
                    { "part": "Platform_Paddle_Type_Sensor" },
                    {
                        "part": "Paddle_Position_Sensor",
                        "config": { name: "left_paddle", paddle: "left" },
                    },
                    {
                        "part": "Paddle_Position_Sensor",
                        "config": { name: "right_paddle", paddle: "right" },
                    },
                    { "part": "Ball_Sensor" },
                ], 
                [
                    { "part": "PaddleController" },
                    { "part": "Platform_Paddle_Type_Sensor" },
                    {
                        "part": "Paddle_Position_Sensor",
                        "config": { name: "left_paddle", paddle: "left" },
                    },
                    {
                        "part": "Paddle_Position_Sensor",
                        "config": { name: "right_paddle", paddle: "right" },
                    },
                    { "part": "Ball_Sensor" },
                ]
            ],

        "episode_parameter_provider":
            {
                "type": "corl.episode_parameter_providers.simple.SimpleParameterProvider",
            },

        "glues":
            [
                [
                    {
                        "functor": "corl.glues.common.controller_glue.ControllerGlue",
                        "config": { "controller": "PaddleController" },
                    },
                    {
                        "functor": "corl.glues.common.observe_sensor.ObserveSensor",
                        "config": { "sensor": "Platform_Paddle_Type_Sensor" },
                    },
                    {
                        "functor": "corl.glues.common.observe_sensor.ObserveSensor",
                        "config": { "sensor": "left_paddle" },
                    },
                    {
                        "functor": "corl.glues.common.observe_sensor.ObserveSensor",
                        "config": { "sensor": "right_paddle" },
                    },
                    {
                        "functor": "corl.glues.common.observe_sensor.ObserveSensor",
                        "config": { "sensor": "Ball_Sensor" },
                    },
                    {
                        "name": "TargetSide",
                        "functor": "corl.glues.common.target_value.TargetValue",
                        "config":
                            {
                                "limit": {
                                    "minimum": {"value": 0, "unit": dimensionless},
                                    "maximum": {"value": 1, "unit": dimensionless},
                                },
                            },
                        "references": { "target_value": "target_side" },
                    },
                ],
                [
                    {
                        "functor": "corl.glues.common.controller_glue.ControllerGlue",
                        "config": { "controller": "PaddleController" },
                    },
                    {
                        "functor": "corl.glues.common.observe_sensor.ObserveSensor",
                        "config": { "sensor": "Platform_Paddle_Type_Sensor" },
                    },
                    {
                        "functor": "corl.glues.common.observe_sensor.ObserveSensor",
                        "config": { "sensor": "left_paddle" },
                    },
                    {
                        "functor": "corl.glues.common.observe_sensor.ObserveSensor",
                        "config": { "sensor": "right_paddle" },
                    },
                    {
                        "functor": "corl.glues.common.observe_sensor.ObserveSensor",
                        "config": { "sensor": "Ball_Sensor" },
                    },
                    {
                        "name": "TargetSide",
                        "functor": "corl.glues.common.target_value.TargetValue",
                        "config":
                            {
                                "limit": {
                                    "minimum": {"value": 0, "unit": dimensionless},
                                    "maximum": {"value": 1, "unit": dimensionless},
                                },
                            },
                        "references": { "target_value": "target_side" },
                    },
                ]
            ],
        "dones":
            [
                {
                    "name": "PongGameDoneFunction",
                    "functor": "corl.dones.pong.commander_pong_dones.CommanderPongGameDoneFunction",
                    "config":
                        {
                            "observation":
                                { "fields": ["paddle_ctrl", "paddle0", 0, "TargetSideTargetValue", "target_value"] },
                        },
                },
                {
                    "name": "PongGameHealthFunction",
                    "functor": "corl.dones.pong.commander_pong_dones.CommanderPongHealthDone",
                },
            ],
        "rewards":
            [
                {
                    "name": "EpisodeDoneState",
                    "functor": "corl.rewards.episode_done.EpisodeDoneStateReward",
                    "config": { "win": 1, "lose": -1, "consolidate": True },
                },
            ],
    }
