# ---------------------------------------------------------------------------
#
#
# Air Force Research Laboratory (AFRL) Autonomous Capabilities Team (ACT3)
# Reinforcement Learning (RL) Core.
#
# This is a US Government Work not subject to copyright protection in the US.
#
# The use, dissemination or disclosure of data in this file is subject to
# limitation or restriction. See accompanying README and LICENSE for details.
# ---------------------------------------------------------------------------
{
    "policy_class": corl.policies.scripted_action.ScriptedActionPolicy,
    "train": False,

    "config": {
            "controllers": [["Controller_Gymnasium_Gymnasium controller"]],

            "time_extractor":
                {
                    "fields": ["Obs_Sensor_State", "direct_observation"],
                    "indices": [4],
                },
            "control_times": [0, 1, 2, 3, 4],
            "controls_list": [[1], [0], [1], [0], [1]],

            "missing_action_policy": "repeat_last_action",
            # Use the default_action policy when repeating the last action may not be suitable
            # e.g. delta controller
            # missing_action_policy: default_action
            # default_action: [0.0, 300, 12000, 0, [0, 0]]
        },
}
